phases:
  install:
    runtime-versions:
      docker: 18
      java: corretto11
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region $AWS_REGION)
  build:
    commands:
      - echo Build started on `date`
      - echo Building java
      - cd pensioner-detail-service
      - mvn clean package
      - echo Building the docker image
      - docker build -t pensioner-detail-service .
      - docker tag pensioner-detail-service 274201610284.dkr.ecr.$AWS_REGION.amazonaws.com/pensioner-detail-service:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - docker push 274201610284.dkr.ecr.$AWS_REGION.amazonaws.com/pensioner-detail-service:latest
      - echo Writing definition files
      - printf '[{"name":"ij028-pensioner-detail-service:latest-container","imageUri":"%s"}]' 274201610284.dkr.ecr.$AWS_REGION.amazonaws.com/pensioner-detail-service:latest > taskdefinition.json



artifacts:
  files: authorization-service/taskdefinition.json